name: Go

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        PAM_SERVER_URL: ${{ secrets.PAM_SERVER_URL }}
        PAM_CLIENT_ID: ${{ secrets.PAM_CLIENT_ID }}
        PAM_CLIENT_SECRET: ${{ secrets.PAM_CLIENT_SECRET }}
        PAM_ACCOUNT_ID: ${{ secrets.PAM_ACCOUNT_ID }}
        PAM_ACCOUNT_USERNAME: ${{ secrets.PAM_ACCOUNT_USERNAME }}
        PAM_ACCOUNT_PASSWORD: ${{ secrets.PAM_ACCOUNT_PASSWORD }}
